# Generated by Django 4.1.4 on 2023-01-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
