# Generated by Django 4.1.4 on 2023-01-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userdata_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='doors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
