# Generated by Django 4.1.4 on 2023-01-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdata_doors_alter_userdata_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='doors',
            field=models.TextField(default=''),
        ),
    ]
