# Generated by Django 4.1.4 on 2023-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userdata_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='doors_command',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='doors_outputs',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='doors',
            field=models.TextField(default='None'),
        ),
    ]
