# Generated by Django 4.1.4 on 2023-01-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userdata_doors_command_userdata_doors_outputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='last_conn',
            field=models.TextField(default='{}'),
        ),
    ]
