# Generated by Django 4.1.4 on 2023-01-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdata_last_conn'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='photo_txt',
            field=models.TextField(default=''),
        ),
    ]
