# Generated by Django 4.1.4 on 2023-01-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userdata_photo_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='photo',
        ),
    ]
