# Generated by Django 4.1.4 on 2023-01-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userdata_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='doors_params',
            field=models.TextField(default='{}'),
        ),
    ]
